from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "src" / "mathgraph_igp24"
OUTPUT = ROOT / "dist" / "mathgraph_igp24_v102_colab.py"
OUTPUT_V109 = ROOT / "dist" / "mathgraph_igp24_v109_survivor_colab.py"
MANIFEST = ROOT / "dist" / "artifact_manifest.json"
CYCLE_RUNNER = ROOT / "scripts" / "run_v102_cycle.py"
SURVIVOR_RUNNER = ROOT / "scripts" / "run_v109_survivor_cycle.py"


def render(runner_path: Path = CYCLE_RUNNER, output: Path = OUTPUT, title: str = "v102 — Provenance Lawbook Scoring Engine") -> tuple[str, dict]:
    sources = {f"mathgraph_igp24/{path.name}": path.read_text(encoding="utf-8") for path in sorted(PACKAGE_ROOT.glob("*.py"))}
    sources[runner_path.name] = runner_path.read_text(encoding="utf-8")
    source_hashes = {name: hashlib.sha256(text.encode()).hexdigest() for name, text in sources.items()}
    module_name = runner_path.stem
    runner = f'''# START GENERATED COLAB RUNNER
# MathGraph IGP24 {title}
# Generated by scripts/build_colab_artifact.py. Do not edit directly.
from __future__ import annotations
import sys as _sys
import tempfile as _tempfile
from pathlib import Path as _Path
_SOURCES = __SOURCES__
def _install():
    root = _Path(_tempfile.mkdtemp(prefix="mathgraph_igp24_colab_"))
    for relative, source in _SOURCES.items():
        target = root / relative; target.parent.mkdir(parents=True, exist_ok=True); target.write_text(source, encoding="utf-8")
    _sys.path.insert(0, str(root)); return root
_EMBEDDED_ROOT = _install()
from mathgraph_igp24 import *  # noqa: F401,F403,E402
from {module_name} import main as _cycle_main  # noqa: E402
def main(): _cycle_main()
if __name__ == "__main__": main()
# END GENERATED COLAB RUNNER
'''.replace("__SOURCES__", repr(sources))
    artifact_hash = hashlib.sha256(runner.encode()).hexdigest()
    return runner, {"artifact": output.name, "artifact_sha256": artifact_hash,
                    "builder": "scripts/build_colab_artifact.py", "schema_version": "2", "source_hashes": source_hashes}


def build() -> tuple[Path, Path]:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    runner, manifest = render()
    OUTPUT.write_text(runner, encoding="utf-8")
    survivor, survivor_manifest = render(SURVIVOR_RUNNER, OUTPUT_V109, "v109 — Survivor Geometry Engine")
    OUTPUT_V109.write_text(survivor, encoding="utf-8")
    combined = {"artifacts": [manifest, survivor_manifest], "schema_version": "3"}
    MANIFEST.write_text(json.dumps(combined, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return OUTPUT, OUTPUT_V109, MANIFEST


if __name__ == "__main__":
    for path in build(): print(path)
