from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = ROOT / "src" / "mathgraph_igp24"
DIST = ROOT / "dist"
OUTPUT = DIST / "mathgraph_igp24_v102_colab.py"
MANIFEST = DIST / "artifact_manifest.json"


def source_files() -> list[Path]:
    return sorted(PACKAGE_ROOT.glob("*.py"), key=lambda path: path.name)


def render() -> tuple[str, dict[str, object]]:
    sources = {
        f"mathgraph_igp24/{path.name}": path.read_text(encoding="utf-8")
        for path in source_files()
    }
    source_hashes = {
        name: hashlib.sha256(text.encode("utf-8")).hexdigest()
        for name, text in sources.items()
    }
    runner = '''# START GENERATED COLAB RUNNER
# MathGraph IGP24 v102 — Replayable Inverse Continuation
# Generated by scripts/build_colab.py. Do not edit this artifact directly.

from __future__ import annotations

import json as _json
import os as _os
import sys as _sys
import tempfile as _tempfile
from pathlib import Path as _Path

_SOURCES = __SOURCES__


def _install_embedded_package():
    root = _Path(_tempfile.mkdtemp(prefix="mathgraph_igp24_v102_"))
    for relative, source in _SOURCES.items():
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(source, encoding="utf-8")
    _sys.path.insert(0, str(root))
    return root


_EMBEDDED_ROOT = _install_embedded_package()

from mathgraph_igp24 import *  # noqa: F401,F403,E402


def main():
    parent_text = _os.environ.get("MATHGRAPH_PARENT", "").strip()
    target_text = _os.environ.get("MATHGRAPH_TARGET", "14010,8").strip()
    if not parent_text:
        print("MathGraph IGP24 v102 ready")
        print("Set MATHGRAPH_PARENT to 25 comma-separated coefficients to request a route.")
        return
    parent = parse_poly(parent_text)
    target_values = tuple(int(value.strip()) for value in target_text.split(","))
    if len(target_values) != 2:
        raise ValueError("MATHGRAPH_TARGET must be t,r")
    rec = recommend(parent, target_values)
    child = replay_law(parent, rec.law)
    assert hash_poly(child) == rec.expected_child_hash
    print(_json.dumps({
        "recommendation_id": rec.recommendation_id,
        "law_id": rec.law.law_id,
        "target_pair": rec.target_pair,
        "expected_child_hash": rec.expected_child_hash,
        "expected_probability": rec.expected_probability,
        "child": child,
        "trust_label": rec.trust_label,
        "rationale": rec.rationale,
    }, indent=2))


if __name__ == "__main__":
    main()

# END GENERATED COLAB RUNNER
'''.replace("__SOURCES__", repr(sources))
    artifact_hash = hashlib.sha256(runner.encode("utf-8")).hexdigest()
    manifest: dict[str, object] = {
        "artifact": OUTPUT.name,
        "artifact_sha256": artifact_hash,
        "builder": "scripts/build_colab.py",
        "source_hashes": source_hashes,
        "schema_version": "1",
    }
    return runner, manifest


def build() -> tuple[Path, Path]:
    runner, manifest = render()
    DIST.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(runner, encoding="utf-8")
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return OUTPUT, MANIFEST


if __name__ == "__main__":
    artifact, manifest_path = build()
    print(artifact)
    print(manifest_path)

